apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi #bộ nhớ của volume
  volumeMode: Filesystem
  storageClassName: standard #quản lý storage
  accessModes:
    - ReadWriteOnce #vì volume là dạng hostPath chỉ chạy trên 1 node nên chỉ cho phép nhiều pod claim tới volume này ở trên node này
  hostPath:
    path: /data
    type: DirectoryOrCreate