apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv #name của persistent volume
  accessModes:
    - ReadWriteOnce
  storageClassName: standard #quản lý storage
  resources:
    requests:
      storage: 1Gi